# Generated by Django 5.2.4 on 2025-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poptavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=30)),
                ('popis', models.TextField(help_text='Popište svůj požadavek nebo zakázku')),
                ('odeslano', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
